# Generated by Django 6.1 on 2026-08-06 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_query', models.CharField(max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('finish_query', models.CharField(max_length=255)),
                ('finish_lat', models.FloatField()),
                ('finish_lon', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('geometry', models.TextField(blank=True, help_text='Encoded polyline string')),
                ('assumptions', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('total_fuel_gallons', models.FloatField()),
                ('total_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='Original OPIS Truckstop ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField(db_index=True, help_text='Used for physical deduplication')),
                ('retail_price', models.DecimalField(decimal_places=3, help_text='USD per gallon', max_digits=6)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'latitude', 'longitude'], name='core_statio_state_b44bc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('distance_from_start_miles', models.FloatField()),
                ('gallons_purchased', models.FloatField()),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.routeplan')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
