# Generated by Django 6.1 on 2026-08-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('finish_lat', models.FloatField()),
                ('finish_lon', models.FloatField()),
                ('distance_miles', models.FloatField()),
                ('duration_minutes', models.FloatField()),
                ('geometry_geojson', models.JSONField(default=dict)),
                ('provider', models.CharField(default='osrm_public', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='routeplan',
            name='geometry',
            field=models.TextField(blank=True, help_text='Encoded polyline string or GeoJSON'),
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('normalized_query', models.CharField(db_index=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized_query', 'provider'], name='core_geocod_normali_9073d4_idx')],
            },
        ),
    ]
