# Generated by Django 6.1 on 2026-08-07 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_routecache_alter_routeplan_geometry_geocodecache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'My Semi', 'Daily Driver'", max_length=100)),
                ('mpg', models.FloatField(default=10.0, help_text='Miles per gallon')),
                ('tank_capacity_gallons', models.FloatField(default=50.0, help_text='Fuel tank capacity in gallons')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default vehicle for this user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehicle Profiles',
            },
        ),
    ]
